language: objective-c
osx_image: xcode11.1
rvm:
    2.2.5

before_install:
    - gem install xcpretty
script:
    - swift package generate-xcodeproj
    - set -o pipefail && xcodebuild test -project Promise-swift.xcodeproj -scheme Promise-swift-Package -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty -c 
    - set -o pipefail && xcodebuild test -project Promise-swift.xcodeproj -scheme Promise-swift-Package -destination 'platform=macOS,arch=x86_64' | xcpretty -c 
